# Generated by Django 2.0.4 on 2018-08-03 02:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField(unique=True)),
                ('fingerprint', models.TextField(unique=True)),
                ('karma', models.IntegerField(default=0)),
                ('is_banned', models.BooleanField(default=False)),
                ('topic_subscriptions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, size=None)),
                ('friends', models.ManyToManyField(blank=True, related_name='followers', to='postoffice.Identity')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_id', models.CharField(help_text='IPFS identity of the node', max_length=255)),
                ('karma', models.IntegerField(default=0)),
                ('is_banned', models.BooleanField(default=False)),
                ('last_manifest_path', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SignedEnvelope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(db_index=True, max_length=512)),
                ('link', models.CharField(help_text='IPFS url containing the message', max_length=512)),
                ('timestamp', models.CharField(max_length=40)),
                ('signature', models.TextField()),
                ('received_timestamp', models.DateTimeField(auto_now_add=True)),
                ('pinned', models.BooleanField(default=False)),
                ('karma', models.IntegerField(default=0)),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='postoffice.Identity')),
                ('transmitted_nodes', models.ManyToManyField(blank=True, help_text='Nodes that have transmitted this message', related_name='transmitted_posts', to='postoffice.Node')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karma', models.SmallIntegerField()),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='postoffice.Identity')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postoffice.SignedEnvelope')),
            ],
        ),
        migrations.AddField(
            model_name='identity',
            name='voted_posts',
            field=models.ManyToManyField(blank=True, related_name='voted_identities', through='postoffice.Vote', to='postoffice.SignedEnvelope'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('identity', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='signedenvelope',
            unique_together={('to', 'link', 'timestamp', 'signer')},
        ),
    ]
