# Generated by Django 2.1 on 2018-08-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='public_key',
            field=models.CharField(help_text='Base64 encoded key for verifying signatures', max_length=77, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(help_text='IPFS url containing the message', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='signature',
            field=models.CharField(max_length=1024),
        ),
    ]
