# Generated by Django 2.0.4 on 2018-08-07 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipfs_hash', models.CharField(max_length=64, unique=True)),
                ('users', models.ManyToManyField(related_name='pinned_assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
