# Generated by Django 2.1 on 2018-08-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postoffice', '0002_auto_20180809_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(blank=True, db_index=True, max_length=576),
        ),
        migrations.AlterField(
            model_name='post',
            name='to',
            field=models.CharField(max_length=512),
        ),
    ]
