# Generated by Django 2.0 on 2018-09-24 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postoffice', '0003_auto_20180815_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identity',
            name='is_banned',
        ),
        migrations.RemoveField(
            model_name='nexus',
            name='is_banned',
        ),
        migrations.AddField(
            model_name='identity',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nexus',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nexus',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='karma',
            field=models.SmallIntegerField(default=0),
        ),
    ]
