query posts($location: String) {
  allPosts(address_Startswith: $location, chainLevel: 0) { edges { node {
      id
      to
      signer {id, publicKey}
      link
      address
      chainLevel
      karma
      file {
        content
        contentType
        size
      }
  }}}
}
