mutation login($username: String!, $password: String!) {
  authentication(input: {username:$username, password: $password}) {
    clientMutationId, user {id, username, email, isStaff, identities {id, publickKey}}
  }
}
