fragment Post on PostNode {
    id
    to
    signer {id, publicKey, email}
    link
    address
    karma
    chainLevel
    receivedTimestamp
    file {
      content
      contentType
      size
    }
    userVote {
      id, karma
    }
}
