mutation registerIdentity ($signed_username: String!, $public_key: String!) {
  registerIdentity (input: {signed_username: $signed_username, public_key: $public_key}) {
    id, public_key, fingerprint, karma
  }
}
