mutation registerIdentity ($signed_username: String!, $public_key: String!) {
  registerIdentity (input: {signedUsername: $signed_username, publicKey: $public_key}) {
    identity {id, publicKey, fingerprint, karma}
  }
}
