mutation registerIdentity ($signedUsername: String!, $publicKey: String!) {
  registerIdentity (input: {signedUsername: $signedUsername, publicKey: $publicKey}) {
    identity {id, publicKey, fingerprint, karma}
  }
}
